"""ORM models for the tables the API uses. The DDL lives in alembic/ (docs/database/schema.sql)."""

from app.models.academic import (
    AcademicTerm,
    Department,
    Intake,
    Module,
    ModuleOffering,
    OfferingLecturer,
    Programme,
    ProgrammeModule,
    Venue,
)
from app.models.admissions import (
    Application,
    ApplicationEvent,
    ApplicationFlag,
    DistrictCode,
    Document,
    DocumentField,
    ExamSitting,
    ExamSubjectResult,
    ZimsecSubject,
)
from app.models.base import Base
from app.models.content import (
    Announcement,
    AnnouncementRead,
    AnnouncementTarget,
    CourseMaterial,
    MaterialDownload,
)
from app.models.finance import FeeDueDate, FeeTransaction, RemarkRequest
from app.models.identity import (
    Notification,
    NotificationDelivery,
    NotificationPreference,
    Person,
    User,
    UserRole,
    WebSession,
)
from app.models.library import LibraryCopy, LibraryItem, LibraryLoan, LibraryReservation, ReadingListItem
from app.models.people import Staff, Student
from app.models.teaching import (
    Assessment,
    Attendance,
    ClassSession,
    Enrolment,
    ModuleResult,
    Submission,
    SubmissionFile,
    TimetableException,
    TimetableSlot,
    UploadSession,
)

__all__ = [
    "Application",
    "ApplicationEvent",
    "ApplicationFlag",
    "DistrictCode",
    "Document",
    "DocumentField",
    "ExamSitting",
    "ExamSubjectResult",
    "ZimsecSubject",
    "AcademicTerm",
    "Announcement",
    "AnnouncementRead",
    "AnnouncementTarget",
    "Assessment",
    "Attendance",
    "ClassSession",
    "Base",
    "CourseMaterial",
    "Department",
    "Enrolment",
    "FeeDueDate",
    "FeeTransaction",
    "Intake",
    "LibraryCopy",
    "LibraryItem",
    "LibraryLoan",
    "LibraryReservation",
    "MaterialDownload",
    "Module",
    "ModuleOffering",
    "ModuleResult",
    "Notification",
    "NotificationDelivery",
    "NotificationPreference",
    "OfferingLecturer",
    "Person",
    "Programme",
    "ProgrammeModule",
    "ReadingListItem",
    "RemarkRequest",
    "Staff",
    "Student",
    "Submission",
    "SubmissionFile",
    "TimetableException",
    "TimetableSlot",
    "User",
    "UploadSession",
    "UserRole",
    "Venue",
    "WebSession",
]
